### ISSUE TITLE
Access denied for large image size

### ISSUE THREAD

**Issue by ameer** [CodeDotJS/instagram-profile-picture#2]
I need large image 1080x1080 but it keeps saying Access denied.

**Comment by CodeDotJS** [comment]
A few hours ago, this API was working really fine. Looks like Instagram made some changes again. 

I need to look into the issue so I'm keeping it open till I fix it. 

Thanks for reporting it! 

`PRs are welcome, in case you are willing to dig into the problem.`

**Comment by CodeDotJS** [comment]
Hi @ameer 

The issue has been fixed. Install the latest version of `instagram-profile-picture` and everything will same as it's mentioned.
