### ISSUE TITLE
BAD TIMESTAMP (caused by unicode non-conversion)

### ISSUE THREAD

**Issue by kaanuki** [CodeDotJS/instagram-profile-picture#6]
Hi.

The plugin is not converting the unicode "\u0026" to "&" and it is causing a "Bad timestamp" error.

 🔧This Fixes the issue... 

ipp.medium('instagram').then(user => {
var r = /\u([\d\w]{4})/gi;
user = user.replace(r, function (match, grp) {
return String.fromCharCode(parseInt(grp, 16)); } );
console.log(user);
// => https://scontent-sit4-1.cdninstagram.com/7...jpg
});

**Comment by kaanuki** [comment]
This Fixes the issue...

ipp.medium('instagram').then(user => {
    var r = /\\u([\d\w]{4})/gi;
    user = user.replace(r, function (match, grp) {
        return String.fromCharCode(parseInt(grp, 16)); } );
    console.log(user);
    // => https://scontent-sit4-1.cdninstagram.com/7...jpg
  });

**Comment by CodeDotJS** [comment]
Your approach to the problem won't give the desired answer. Try the solution given below, it should work - 

```js
const ipp = require('instagram-profile-picture');

ipp('instagra').then(user => {
  const img = user.replace(/\\u[\dA-Fa-f]{4}/g, '&');
  console.log(img);
});
```

Additionally, if you'd like to fix this module, you can send me a PR.

Thank you.
